version: '3'

services:
  nginx:
    container_name: serve
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '8100:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysqlASW
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coderace